### ISSUE TITLE
Evernote Similar Search Alignment Issue

### ISSUE THREAD

**Issue by zhaocai** [jmlntw/google-search-sidebar#16]
This issue relates to the alignment problem of the evernote similar search block as below:

![](https://z-1258356203.cos.ap-chengdu.myqcloud.com/img/share/Evernote-simSearchFrame-Issue-20190620131748.png)

I find a quick fix by adding the following lines. Can you update the mainstream?

```css
#simSearchFrame {
  margin-left: calc(-1 * (var(--user-sidebar-width) / 2)) !important;
}
```
